version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/labstack/echo/v4
    versions:
    - 4.2.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
