# NOTE: myriag and myriad confgs are not interchangable.
# There are subtle diferences, namely:
#   - you have to spell out you mean bytes so it's 256mb instead of 256m.
#   - languages field is not object array but a nested object.

# Whether to build images concurrently.
# This will take up more resources when building all the images for the first time.
buildConcurrently: true

# Whether to start containers on startup of myriag.
prepareContainers: false

# Interval in minutes to kill all running languages containers.
cleanupInterval: 30

# Port to run myriag on.
port: 5000

# Host to run myriag on.
host: "127.0.0.1"

# The default language configuration.
defaultLanguage:
    # The maximum memory and swap usage (separately) of a container.
    memory: 256mb

    # The number of CPUs to use.
    cpus: 0.25

    # Time in seconds for an evaluation before the container kills itself.
    timeout: 20

    # The maximum number of concurrent evaluations in the container.
    concurrent: 5

    # The maximum number of retries when the evaluation fails due to a non-timeout related reason.
    retries: 10

    # The maximum number of bytes that can be outputted.
    outputLimit: 4kb

# The languages to enable.
# The fields available are the same as in 'defaultLanguage'.
# The names are as in your 'languages' folder.
languages:
    apl:
        memory: 512mb
        cpus: 0.5
        timeout: 10
        concurrent: 10
        retries: 5
        outputLimit: 8kb
    bash:
    brainfuck:
    c:
    cpp:
    csharp:
    elixir:
    erlang:
    fsharp:
    go:
    haskell:
    idris:
    java:
    javascript:
    julia:
    lua:
    nim:
    ocaml:
    pascal:
    perl:
    php:
    prolog:
    python:
    r:
    racket:
    ruby:
    rust:
    typescript: